from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import AddCourseView, MyCoursesView, LoginView

urlpatterns = [
    path('', views.std_login, name='std_login'),
    # path('', views.LoginView.as_view(), name='std_login'),
    # path('my/', views.myCourses, name='myCourses'),
    path('my/', MyCoursesView.as_view(), name='myCourses'),
    path('facultyCourses/', views.facultyCourses, name='facultyCourses'),
    # path('login/', LoginView.as_view(), name='std_login'),
    path('login/', views.std_login, name='std_login'),
    path('logout/', views.std_logout, name='std_logout'),
    path('my/<int:code>/', views.course_page, name='course'),
    path('profile/<str:id>/', views.profile, name='profile'),
    path('facultyProfile/<str:id>/', views.profile, name='profile_faculty'),
    path('faculty/<int:code>/', views.course_page_faculty, name='faculty'),
    path('addAnnouncement/<int:code>/',
         views.addAnnouncement, name='addAnnouncement'),
    path('announecement/<int:code>/<int:id>/',
         views.deleteAnnouncement, name='deleteAnnouncement'),
    path('edit/<int:code>/<int:id>/',
         views.editAnnouncement, name='editAnnouncement'),
    path('update/<int:code>/<int:id>/',
         views.updateAnnouncement, name='updateAnnouncement'),
    path('addAssignment/<int:code>/', views.addAssignment, name='addAssignment'),
    path('assignment/<int:code>/<int:id>/',
         views.assignmentPage, name='assignmentPage'),
    path('assignments/<int:code>/', views.allAssignments, name='allAssignments'),
    path('student-assignments/<int:code>/',
         views.allAssignmentsSTD, name='student-assignments'),
    path('addSubmission/<int:code>/<int:id>/',
         views.addSubmission, name='addSubmission'),
    path('submission/<int:code>/<int:id>/',
         views.viewSubmission, name='submission'),
    path('gradeSubmission/<int:code>/<int:id>/<int:sub_id>',
         views.gradeSubmission, name='gradeSubmission'),
    path('course-material/<int:code>/',
         views.addCourseMaterial, name='addCourseMaterial'),
    path('course-material/<int:code>/<int:id>/',
         views.deleteCourseMaterial, name='deleteCourseMaterial'),
    path('courses/', views.courses, name='courses'),
    path('departments/', views.departments, name='departments'),
    path('access/<int:code>/', views.access, name='access'),
    path('changePasswordPrompt/', views.changePasswordPrompt,
         name='changePasswordPrompt'),
    path('changePhotoPrompt/', views.changePhotoPrompt, name='changePhotoPrompt'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('changePasswordFaculty/', views.changePasswordFaculty,
         name='changePasswordFaculty'),
    path('changePhoto/', views.changePhoto, name='changePhoto'),
    path('changePhotoFaculty/', views.changePhotoFaculty,
         name='changePhotoFaculty'),
    path('search/', views.search, name='search'),
    path('error/', views.error, name='error'),
    path('payment/<int:course_code>/', views.payment, name='payment'),
    path('membership/', views.membership, name='membership'),
    path('membership_payment/<int:selected_membership_pk>/', views.membership_payment, name='membership_payment'),
    path('access_courses/<int:code>/', views.access_courses, name='access_courses'),
    path('signup/', views.signup, name='signup'),  # Signup page URL
    # path('add_course/', views.add_course, name='add_course'),
    path('add_course/', AddCourseView.as_view(), name='add_course'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='main/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='main/password_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='main/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='main/password_reset_complete.html'), name='password_reset_complete'),
    path('reset/<uidb64>/<token>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('password_reset_view/', views.password_reset_view, name='password_reset_view'),
    path('password_error/', auth_views.PasswordResetDoneView.as_view(template_name='main/password_error.html'), name='password_error'),
    # Other URL patterns
]


